### PR TITLE
use CompositeSubscription to avoid memory leak

### PR DESCRIPTION
**Pull request by gengjiawen**
check this: http://blog.danlew.net/2014/10/08/grokking-rxjava-part-4/.
I think use CompositeSubscription to avoid memory leak is a good practice, especially when you have multi subscriptions.

### CODE REVIEW

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by jemmaSlater** [comment]
Hi. Thanks for the pull request!

I've done a little bit of research into if this would be a good addition to our boilerplate. In our production apps, we have sometimes used CompositeSubscription and there are definitely some benefits to using this instead of lots of Subscriptions when you are deep in a project. 

There are a couple of points holding me back from merging this however, but I'm open to discussion!

1. This is just a boilerplate project from which we aim to make it as easy as possible to start any project. The methods contained within are meant just as an example of how it all fits together. In this class currently, as it is, I can not see any benefit to adding CompositeSubscription.

2. I am not sure, at this boilerplate stage, that we should be showing a preference of using .clear() or .unsubscribe(). I think there are use cases for using both depending on what you want to do and prescribing this in the boilerplate may lead to incorrect usage in other projects. This blog post helps show the difference between the two: http://www.paul-woitaschek.de/blog/when-to-use-composite-subscription-unsubscribe/

3. I have read the blog you linked. I am not convinced that it is the CompositeSubscription itself which helps avoid the memory leak. As far as I can see, having glanced at the source code, the benefit of using CompositeSubscription is that you can easily unsubscribe from multiple subscriptions at the same time. I think the memory leak issue mentioned is already handled by calling .unsubscribe() in the onDetach() method which is called on onDestroy() - as far as I can see this is the solution that the blog post was suggesting, rather than it having to be done with CompositeSubscriptions..

**Comment by gengjiawen** [comment]
Yes, it's may not appropriate for this project.I am okay with that we stay with old way.

However compositeSubscription do help with the memory leak problem.Because I add leakcanary to our company's project (which have adopted this project most open source library, much thanks :) ).I have a countdown observable.IF I leave the activity when the countdown still running, leakcanary will detect a memory leak.After i use CompositeSubscription, the leak problem is fixed.

And google's official android-architecture use the same way [sample file](https://github.com/googlesamples/android-architecture/blob/d48378bf4b5dcf65b005a8b0c48d08fc22ddbd7c/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/StatisticsPresenter.java)

**Comment by jemmaSlater** [comment]
Okay, great thanks. I am going to close this pull request now then without merging.

Will take a look at the google samples and keep it in mind for the future. Thanks for your thoughts. :)

**Pull request closed without merging**
