### PR TITLE
Replace deprecated RxJava methods.

### PR DESCRIPTION
**Pull request by viniciussoares**
As mentioned by @jemmaSlater [here](https://github.com/ribot/android-boilerplate/pull/67#issuecomment-272835881), there was a bunch of deprecated methods within the existing code, most of them related to the old RxJavaPlugins api.

https://github.com/ReactiveX/RxJava/pull/4007

### CODE REVIEW

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by jemmaSlater** [comment]
Thanks for updating these, I'm happy to merge them in without any changes!

However, the deprecated methods I was referring to [previously](https://github.com/ribot/android-boilerplate/pull/67#issuecomment-272835881) in relation to the Mockito update were as follows:
 - `org.mockito.runners.MockitoJUnitRunner` -> The import now needs to be changed to `org.mockito.junit.MockitoJUnitRunner`
 - `anyListOf(java.lang.Class<T>)` -> Used in a couple of our tests, now deprecated will need to be changed to use the `anyList()` method. eg: `anyListOf(Ribot.class)` -> `ArgumentMatchers.<Ribot>anyList()`

Feel free to make another pull request with these updates if you like, but thanks for updating the RxJavaPlugins which were also on our todo list! 👍

**Comment by viniciussoares** [comment]
Happy to help :) The todo list is public? Maybe i can help.

**Comment by jemmaSlater** [comment]
No public todo list I'm afraid - just generally trying to keep everything up to date, and was aware RxJavaPlugins needed updating!

**Pull request merged**
