### PR TITLE
Update SqlBrite to 1.1.1.

### PR DESCRIPTION
**Pull request by viniciussoares**
Update SqlBrite to the latest version.

### CODE REVIEW

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by jemmaSlater** [comment]
Thanks for the pull request!

I'm not convinced we need to add logs here in the boilerplate. It adds quite a bit of noise to the log output and we usually try to minimise the number of logs we leave in production code - so adding the logger here is something which can be added on an as needed basis, and is not necessary for the boilerplate code.

Is there a particular reason why you think it would be useful to add this logger to the boilerplate?

Also, for the logger to work in this case you also need to add this line `mDb.setLoggingEnabled(true);` just after you've assigned mDb. 🙂

**Comment by viniciussoares** [comment]
No particular reason, just to showcase the feature :) 

But i don't think it will output this messages on the production build (I need to check), because Timber.DebugTree is only "planted" in debug builds.

I'll update the pull request removing the log :D

**Comment by viniciussoares** [comment]
@jemmaSlater i've just updated the pull request :) Sorry about the delay.

**Comment by jemmaSlater** [comment]
Thanks for updating!

It is great to showcase features, we just have to keep in mind that the purpose of this project is to provide a bare-boned boilerplate from which new projects can be built upon. 🙂

**Pull request merged**
