### PR TITLE
RxJavaPlugins.getInstance() is depreceted

### PR DESCRIPTION
**Pull request by MohamedISoliman**
remove mRxJavaSchedulersHook instance, using RxjavaHooks static methods instead.

### CODE REVIEW

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by jemmaSlater** [comment]
Hey, thanks for opening a pull request!

I have checked out your branch but unfortunately have found a couple of issues.

- The import for `RxJavaHooks` has not been added to the class.
- The now unused `RxJavaPlugins` import has not been removed.
- The ribot style guidelines regarding indent spacing have not been followed (line 22 should have a 4 space indent).
- The unit tests no longer pass once these changes have been made. (Unfortunately we do not have a public CI client currently set up, but the tests can be run locally).

Do the tests pass for you?

I have had a look into how we can fix this to allow it to be merged, and have found a good example in an open source project by @Plastix which can be seen here: https://github.com/Plastix/RxSchedulerRule/blob/master/rx1/src/main/java/io/github/plastix/rxschedulerrule/RxSchedulerRule.java

What do you think?

**Comment by MohamedISoliman** [comment]
I've downloaded the project and worked on it locally, made those changes on github only. so accidentally forget to change imports.
also I've run the `DatabaseHelperTest` and passed without any problem, for now it's what I'm working on.
@Plastix  class seems to be a good implementation too, but I think that we don't need final `RxJavaSchedulerHook` instance as we can just use the static methods directly with `Schedulers.immediate();` . may it is doing the same thing in different ways.

**Comment by jemmaSlater** [comment]
Sorry, should have specified - only the `loadRibotsReturnsRibots` and the `loadRibotsReturnsEmptyList` tests in the `MainPresenterTest` class are failing with these changes. Are these tests passing for you?

The `DatabaseHelperTest` class does not contain any tests which use the `IOScheduler` or the `NewThreadScheduler` which is why these tests are still passing in this case.


The difference seems to be that whereas the deprecated method happily accepted a Scheduler as a parameter, according to the documentation (https://github.com/ReactiveX/RxJava/wiki/Plugins#rxjavahooks) the new way requires `Func1<Scheduler, Scheduler>`. Therefore it does not appear to be enough to simply pass in `Schedulers.immediate()` in this way, and instead passing in a function appears to be required.

It seems to be more flexible to use the 'set' methods and pass in the Func1 parameter, like below: 

```
RxJavaHooks.setOnIOScheduler(new Func1<Scheduler, Scheduler>() {
                    @Override
                    public Scheduler call(Scheduler scheduler) {
                        return Schedulers.immediate();
                    }
                });
```

**Comment by MohamedISoliman** [comment]
thanks for mentioning the documentation, I will use @Plastix implementation for now, if something went wrong with tests , I will make another pull .. keep up your awesome work guys 👍

**Pull request closed without merging**
