### PR TITLE
feat: Add method that appends an Interceptor to OkHttpClient instances

### PR DESCRIPTION
**Pull request by Jventajas**
I added a method that adds Interceptors to OkHttpClient instances.

It is useful when, for example, all your api calls need to have a query parameter.

### CODE REVIEW

**Comment by barykaed** [comment]
Looks good i think.. i'm using something similar for adding my auth  tokens... I'll try to add a pull request soon with some interceptors for headers.

**Comment by Jventajas** [comment]
Yeah, it's nothing fancy but helps to keep the code simpler. By the way, I'm a fellow nanodegree graduate :)

**Comment by ivacf** [comment]
Hi Javier,

This looks good and it is useful, however I personally don't think this should be added to this boilerplate. We're trying to keep this project as simple as possible so we can just use it as a starting point for new project. Some new projects my not require this method, or some people may want to append their headers in a different way.

But thanks for the pull request!

**Comment by Jventajas** [comment]
Nevermind, I understand. If you are working on a feature or an issue right now, I'd be more than happy to collaborate, though.

Cheers!

**Comment by ivacf** [comment]
Thanks for understanding! I'm going to close this.

**Pull request closed without merging**
