### PR TITLE
Add a mechanism to create issues, API is also down.

### PR DESCRIPTION
**Pull request by Danm72**
FYI https://api.ribot.io/ is down, nginx 503 response.

### CODE REVIEW

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by jemmaSlater** [comment]
Hello!

Thanks for alerting us to the site being down, it should be back up again now. 👍 

I will add something to the readme about being open for contributions. :)

**Comment by jemmaSlater** [comment]
We now have a [contribution file](https://github.com/ribot/android-boilerplate/blob/master/CONTRIBUTING.md) 👍

**Comment by Danm72** [comment]
Great!
I wanted to make an issue yesterday, and that doesn't seem to be available,
maybe to do with this repo being a fork. 

Is there any way to re-enable this or document an alternative issues flow?
Cheers  





On Fri, Feb 24, 2017 12:27 PM, jemmaSlater notifications@github.com  wrote:
We now have a contribution file  👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Dan

Director@Mawla

**Comment by jemmaSlater** [comment]
What is the issue you are having? Feel free to propose a solution by opening a pull request and we can try to work through it together..

**Pull request closed without merging**
