### PR TITLE
Port to RxJava 2.

### PR DESCRIPTION
**Pull request by viniciussoares**
Since RxJava 1 entered in a feature freeze mode on June 1, 2017; this PR ports the app to the new and shining RxJava 2 xD

Notes:
* This PR depends on #75 .
* I didn't use Flowable, Single and Completable yet to make the transition smoother.

### CODE REVIEW

**Comment by madnotdead** [comment]
Any new abot this PR? I havent seen any movement in this repo

**Comment by ribotaccounts** [comment]
Can one of the admins verify this patch?

**Comment by riinav** [comment]
Can this PR be merged? It hasn't moved and no reply till date

**Comment by viniciussoares** [comment]
Done :smile: Conflicts resolved and typos fixed.
Thank you guys for this amazing project, i'm always happy to help.

I'm hoping to be able to contribute more when the Architecture Components reach a stable release.

**Pull request merged**
